"""
Market Maker Agent - Provides liquidity by quoting both sides
"""
import numpy as np
from .base_agent import BaseAgent

class MarketMakerAgent(BaseAgent):
    """Agent that provides liquidity by placing limit orders on both sides"""
    
    def __init__(self, agent_id=None, cash=10000.0, inventory=0.0,
                 spread_factor=0.002, inventory_skew_factor=0.001,
                 base_order_size=5):
        """
        Initialize market maker
        
        Args:
            agent_id: Unique identifier
            cash: Initial cash balance
            inventory: Initial asset inventory
            spread_factor: Bid-ask spread as fraction of mid price
            inventory_skew_factor: Price adjustment based on inventory
            base_order_size: Base quantity for orders
        """
        super().__init__(agent_id, cash, inventory)
        self.spread_factor = spread_factor
        self.inventory_skew_factor = inventory_skew_factor
        self.base_order_size = base_order_size
        self.active_orders = {'bid': None, 'ask': None}
        self.rng = np.random.default_rng()
        
    def get_action(self, snapshot):
        """
        Generate market making actions (cancel old, place new quotes)
        
        Args:
            snapshot: Market snapshot
            
        Returns:
            List of order actions (cancel and new orders)
        """
        actions = []
        
        # Cancel existing orders if they exist
        for side, order_id in self.active_orders.items():
            if order_id:
                actions.append({
                    'type': 'cancel',
                    'order_id': order_id,
                    'agent_id': self.id
                })
        
        # Calculate quote prices with inventory skew
        if snapshot and 'mid_price' in snapshot and snapshot['mid_price'] > 0:
            mid_price = snapshot['mid_price']
            
            # Inventory skew: adjust prices based on inventory
            # Positive inventory → lower ask, higher bid to reduce inventory
            # Negative inventory → higher ask, lower bid to increase inventory
            inventory_skew = self.inventory * self.inventory_skew_factor * mid_price
            
            # Calculate spread
            half_spread = self.spread_factor * mid_price / 2
            
            # Bid price (price to buy)
            bid_price = mid_price - half_spread - inventory_skew
            bid_price = max(0.01, bid_price)  # Ensure positive price
            
            # Ask price (price to sell)
            ask_price = mid_price + half_spread - inventory_skew
            ask_price = max(bid_price + 0.01, ask_price)  # Ensure ask > bid
            
            # Determine order sizes based on inventory
            bid_quantity = self.base_order_size
            ask_quantity = self.base_order_size
            
            # Adjust quantities based on inventory constraints
            max_bid_quantity = int(self.cash / bid_price)
            bid_quantity = min(bid_quantity, max_bid_quantity)
            
            ask_quantity = min(ask_quantity, int(self.inventory))
            
            # Only place orders if we have capacity
            if bid_quantity > 0:
                bid_order = {
                    'type': 'new',
                    'agent_id': self.id,
                    'side': 'buy',
                    'quantity': bid_quantity,
                    'price': bid_price,
                    'order_type': 'limit',
                    'timestamp': snapshot.get('timestamp', 0)
                }
                actions.append(bid_order)
            
            if ask_quantity > 0:
                ask_order = {
                    'type': 'new',
                    'agent_id': self.id,
                    'side': 'sell',
                    'quantity': ask_quantity,
                    'price': ask_price,
                    'order_type': 'limit',
                    'timestamp': snapshot.get('timestamp', 0)
                }
                actions.append(ask_order)
            
            # Store order IDs for future cancellation (simplified - IDs generated by engine)
            self.active_orders = {'bid': 'pending', 'ask': 'pending'}
        
        return actions if actions else None